// <auto-generated />
using System;
using DPUMenzil.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DPUMenzil.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DPUMenzil.Core.Entities.Gonderi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AnonimMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Durum")
                        .HasColumnType("integer");

                    b.Property<string>("Icerik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("KategoriId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OlusturanKullaniciId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OlusturulmaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tur")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.HasIndex("OlusturanKullaniciId");

                    b.ToTable("Gonderiler");
                });

            modelBuilder.Entity("DPUMenzil.Core.Entities.Kategori", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a1b-8c2d-1e2f3a4b5c6d"),
                            Aciklama = "Yemek listesi ve kalite geri bildirimleri",
                            Ad = "Yemekhane"
                        },
                        new
                        {
                            Id = new Guid("b2c3d4e5-f6a1-4b2c-9d3e-2f3a4b5c6d7e"),
                            Aciklama = "Kampüs içi ulaşım ve saatler",
                            Ad = "Ring Seferleri"
                        },
                        new
                        {
                            Id = new Guid("c3d4e5f6-a1b2-4c3d-0e4f-3a4b5c6d7e8f"),
                            Aciklama = "Çalışma alanları ve kaynaklar",
                            Ad = "Kütüphane"
                        },
                        new
                        {
                            Id = new Guid("d4e5f6a1-b2c3-4d4e-1f5a-4b5c6d7e8f9a"),
                            Aciklama = "Kampüs güvenliği ve acil durumlar",
                            Ad = "Güvenlik"
                        },
                        new
                        {
                            Id = new Guid("e5f6a1b2-c3d4-4e5f-2a6b-5c6d7e8f9a0b"),
                            Aciklama = "Dersler ve sınav süreçleri hakkında",
                            Ad = "Akademik"
                        });
                });

            modelBuilder.Entity("DPUMenzil.Core.Entities.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Eposta")
                        .IsUnique();

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("DPUMenzil.Core.Entities.Gonderi", b =>
                {
                    b.HasOne("DPUMenzil.Core.Entities.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DPUMenzil.Core.Entities.Kullanici", "OlusturanKullanici")
                        .WithMany("Gonderiler")
                        .HasForeignKey("OlusturanKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Kategori");

                    b.Navigation("OlusturanKullanici");
                });

            modelBuilder.Entity("DPUMenzil.Core.Entities.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });

            modelBuilder.Entity("DPUMenzil.Core.Entities.Kullanici", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
